name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # 当main分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'  # 这里可以指定具体版本号，如'0.119.0'
          extended: true          # 是否使用extended版本

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo生成的静态文件目录
